columns:
    - Item_Identifier: str,
    - Item_Weight: float,
    - Item_Fat_Content: str,
    - Item_Visibility: float,
    - Item_Type: category,
    - Item_MRP: float,
    - Outlet_Identifier: category,
    - Outlet_Establishment_Year: int,
    - Outlet_Size: category,
    - Outlet_Location_Type: category,
    - Outlet_Type: category,
    - Item_Outlet_Sales: float


drop_columns:
    - Item_Identifier


numerical_columns:
    - Item_Weight
    - Item_Visibility
    - Item_MRP
    

categorical_columns:
    - Item_Fat_Content
    - Item_Type
    - Outlet_Establishment_Year
    - Outlet_Type
    - Outlet_Identifier
    - Outlet_Size
    - Outlet_Location_Type