columns:
    - Item_Outlet_Sales: float
    - Item_Identifier: str,
    - Item_Weight: float,
    - Item_Fat_Content: str,
    - Item_Visibility: float,
    - Item_Type: str,
    - Item_MRP: float,
    - Outlet_Identifier: str,
    - Outlet_Establishment_Year: int,
    - Outlet_Size: str,
    - Outlet_Location_Type: str,
    - Outlet_Type: str,

drop_columns:
    - Item_Identifier


numerical_columns:
    - Item_Weight
    - Item_Visibility
    - Item_MRP
    - Item_Outlet_Sales

categorical_columns:
    - Item_Fat_Content
    - Item_Type
    - Outlet_Establishment_Year
    - Outlet_Type
    - Outlet_Identifier
    - Outlet_Size
    - Outlet_Location_Type